#!/bin/sh
# shellcheck shell=sh
# render-pr.sh: deterministic rendering of phase 6's commit message, PR body,
# labels, and `gh pr create` call, from the driver's `ready_for_pr` payload
# (fix-group.sh score, exit 0) and the group JSON (issue #172).
#
# Byte-equality is asserted against fixture files under
# spec/fixtures/render-pr/ rather than substring matching, per CLAUDE.md's
# "assert JSON/text exactly" rule extended to this script's rendered text.

Describe 'render-pr.sh'
  RENDER="$COMMON/render-pr.sh"
  FX="$FIXTURES/render-pr"
  REPO="octo/app"

  # Every expected-*.md/.txt fixture was generated by this script and hand
  # reviewed against the template in agents/fix-dependency.md's old phase 6;
  # a regression that changes rendering must update the fixture deliberately,
  # not accidentally pass by comparing the script against itself.
  render_commit_msg() {
    "$RENDER" commit-msg --state "$FX/$1" --group-json "$FX/group.json" --repo "$REPO"
  }
  render_body() {
    state=$1
    shift
    "$RENDER" body --state "$FX/$state" --group-json "$FX/group.json" --repo "$REPO" "$@"
  }

  Describe 'commit-msg'
    It 'renders the scoped-override template byte-for-byte'
      When call render_commit_msg state-scoped.json
      The status should be success
      The output should equal "$(cat "$FX/expected-commit-msg-scoped.txt")"
    End

    It 'renders the direct-update template, falling back to GHSA when cve is null'
      When call render_commit_msg state-direct.json
      The status should be success
      The output should equal "$(cat "$FX/expected-commit-msg-direct.txt")"
    End

    It 'renders the bare-override template'
      When call render_commit_msg state-bare-added.json
      The status should be success
      The output should equal "$(cat "$FX/expected-commit-msg-bare-added.txt")"
    End

    It 'emits one Refs: line per alert, in alert order'
      When call render_commit_msg state-scoped.json
      The status should be success
      The output should include "Refs: https://github.com/octo/app/security/dependabot/42
Refs: https://github.com/octo/app/security/dependabot/55"
    End

    It 'refuses a lockfile-refresh action: nothing to commit beyond the drift commit'
      When call render_commit_msg state-lockfile-refresh.json
      The status should equal 1
      The output should include '"error"'
      The output should include 'lockfile-refresh'
      The stderr should include 'lockfile-refresh'
    End

    It 'refuses a missing --state file'
      When run script "$RENDER" commit-msg --state "$FX/no-such-file.json" --group-json "$FX/group.json" --repo "$REPO"
      The status should equal 1
      The output should include '"error"'
      The stderr should include 'no such file'
    End
  End

  Describe 'body — every documented variant, byte-for-byte'
    Parameters
      state-scoped.json            expected-body-scoped.md
      state-direct.json            expected-body-direct.md
      state-lockfile-refresh.json  expected-body-lockfile-refresh.md
      state-drift.json             expected-body-drift.md
      state-pnpm.json              expected-body-pnpm.md
      state-major-bump.json        expected-body-major-bump.md
      state-major-bump-pnpm.json   expected-body-major-bump-pnpm.md
      state-major-bump-yarn.json   expected-body-major-bump-yarn.md
      state-collateral-null.json   expected-body-collateral-null.md
      state-collateral-benign.json expected-body-collateral-benign.md
    End

    It "renders $1 as $2"
      When call render_body "$1"
      The status should be success
      The output should equal "$(cat "$FX/$2")"
    End
  End

  Describe 'body — variants requiring a supplied narrative note'
    It 'renders the bare-added Global override section with --global-override-note'
      When call render_body state-bare-added.json --global-override-note "$FX/global-override-note.txt"
      The status should be success
      The output should equal "$(cat "$FX/expected-body-bare-added.md")"
    End

    It 'renders the bare-tightened Global override section with --global-override-note'
      When call render_body state-bare-tightened.json --global-override-note "$FX/global-override-note.txt"
      The status should be success
      The output should equal "$(cat "$FX/expected-body-bare-tightened.md")"
    End

    It 'renders the fatal Collateral table plus the supplied narrative with --collateral-note'
      When call render_body state-collateral-fatal.json --collateral-note "$FX/collateral-note.txt"
      The status should be success
      The output should equal "$(cat "$FX/expected-body-collateral-fatal.md")"
    End
  End

  Describe 'body — a required note that was not supplied is a clear error, not invented prose'
    It 'refuses bare_override != none with no --global-override-note'
      When call render_body state-bare-added.json
      The status should equal 1
      The output should include '"error"'
      The output should include '--global-override-note'
      The stderr should include '--global-override-note'
    End

    It 'refuses a fatal other_line_moves entry with no --collateral-note'
      When call render_body state-collateral-fatal.json
      The status should equal 1
      The output should include '"error"'
      The output should include '--collateral-note'
      The stderr should include '--collateral-note'
    End

    It 'prints nothing but the error on a missing global-override note (no partial body)'
      When call render_body state-bare-added.json
      The status should equal 1
      The line 1 of output should equal '{'
      The stderr should include '--global-override-note'
    End
  End

  Describe 'body — omits Not fixed by this PR when requires_major_bump is empty'
    It 'never renders the section for the scoped fixture'
      When call render_body state-scoped.json
      The status should be success
      The output should not include '## Not fixed by this PR'
    End

    It 'renders it for the major-bump fixture, naming the alert and the parent'
      When call render_body state-major-bump.json
      The status should be success
      The output should include '## Not fixed by this PR'
      The output should include "| 3.18.1 | GHSA-p6mc-m468-83gw | no patched release in the 3.x line; needs a major bump of \`some-tool\` or dropping it |"
    End
  End

  # A parent name is only derivable from an npm-shaped install path
  # (node_modules/<parent>/node_modules/<pkg>). pnpm's <pkg>@<version> and
  # Yarn Berry's <pkg>@npm:<version> both name the violating copy itself, not
  # a parent — so on those two managers the cell must say a major bump is
  # needed WITHOUT naming a parent nobody could determine, never an empty or
  # invented identifier. Mirrors fix-group.sh's parent_derivation discipline;
  # rows land specimens for all three managers.
  Describe 'body — Not fixed by this PR derives a parent only where the path names one'
    Parameters
      npm  state-major-bump.json      "needs a major bump of \`some-tool\` or dropping it"
      pnpm state-major-bump-pnpm.json "needs a major bump of the dependent that pins it (not derivable from this report) or dropping it"
      yarn state-major-bump-yarn.json "needs a major bump of the dependent that pins it (not derivable from this report) or dropping it"
    End

    It "renders the honest remediation for a $1-shaped violation path"
      When call render_body "$2"
      The status should be success
      The output should include "$3"
    End
  End

  Describe 'body — pnpm and yarn never fabricate a parent name'
    It 'never renders an empty backtick pair for a pnpm-shaped path'
      When call render_body state-major-bump-pnpm.json
      The status should be success
      The output should not include '`` or dropping it'
      The output should not include 'of `` or'
    End

    It 'never renders an empty backtick pair for a yarn-shaped path'
      When call render_body state-major-bump-yarn.json
      The status should be success
      The output should not include '`` or dropping it'
      The output should not include 'of `` or'
    End
  End

  # A wrongly rendered PR body is a false claim about a security fix, so
  # every "render something plausible from data we could not read" path is a
  # correctness bug, not cosmetics (PR #178 review). Each example here
  # asserts the VERDICT — non-zero exit and a `{"error": ...}` on stdout,
  # nothing else — never the parse, and never a partial body ahead of the
  # error. `render_body`/`render_commit_msg` are not reused where a case
  # needs a non-default --group-json.
  render_body_g() {
    state=$1
    group=$2
    shift 2
    "$RENDER" body --state "$FX/$state" --group-json "$FX/$group" --repo "$REPO" "$@"
  }
  render_commit_msg_g() {
    "$RENDER" commit-msg --state "$FX/$1" --group-json "$FX/$2" --repo "$REPO"
  }
  # Every failure prints ONLY the {"error": ...} object — no markdown, no
  # commit-message fragment, ahead of it (finding #1's "die inside a command
  # substitution never exits" defect, and its class). Inlined at every call
  # site rather than a shared helper: shellspec's `The ...` DSL lines are
  # parsed as part of an `It...End` block and cannot be factored into a
  # plain shell function call.

  Describe 'finding #1: an unreadable --state or --group-json must exit non-zero, never render'
    It 'refuses a non-JSON --state file in body (die inside a command substitution never exits)'
      When call render_body malformed.txt
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should not include 'Lockfile validated'
      The output should not include 'by updating'
    End

    It 'refuses a non-JSON --state file in commit-msg'
      When call render_commit_msg malformed.txt
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End

    It 'refuses a non-JSON --group-json file in body'
      When call render_body_g state-scoped.json malformed.txt
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End

    It 'refuses a non-JSON --group-json file in commit-msg'
      When call render_commit_msg_g state-scoped.json malformed.txt
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End
  End

  Describe 'finding #2: every promised --state field is required, never read with a bare jq -r default'
    Parameters
      state-missing-action.json           ".action"
      state-missing-resolved-version.json ".resolved_version"
      state-missing-drift-commit.json     ".drift_commit"
      state-missing-bare-override.json    ".bare_override"
      state-missing-risk-markdown.json    ".risk.markdown"
      state-missing-why-raw.json          ".why_raw"
      state-missing-written.json          ".written"
      state-missing-validate-checked.json ".validate.checked"
    End

    It "refuses a --state missing $2 rather than rendering the literal string null"
      When call render_body "$1" --global-override-note "$FX/global-override-note.txt" --collateral-note "$FX/collateral-note.txt"
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should not include '## Summary'
    End
  End

  Describe 'finding #3: validate.checked == 0 is never a passing Lockfile-validated claim'
    It 'refuses rather than ticking the box on zero checked, matching the repo'"'"'s zero-found-is-never-a-pass rule'
      When call render_body state-zero-checked.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should include 'checked: 0'
      The output should not include '[x] Lockfile validated: 0'
    End
  End

  Describe 'finding #4: a missing drift_commit can no longer silently drop the drift sentence'
    It 'is covered by finding #2'"'"'s state-missing-drift-commit.json case: require_field now refuses it outright'
      When call render_body state-missing-drift-commit.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End

    It 'still renders the sentence when drift_commit is genuinely true (regression check)'
      When call render_body state-drift.json
      The status should be success
      The output should include 'no-change lockfile refresh'
    End
  End

  Describe 'finding #5: zero-found renders as an error, never a silent empty section'
    It 'refuses an empty group.alerts[] in body rather than rendering "Resolves 0 alert(s)"'
      When call render_body_g state-scoped.json group-empty-alerts.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should not include 'Resolves 0'
    End

    It 'refuses an empty group.alerts[] in commit-msg for the same reason'
      When call render_commit_msg_g state-scoped.json group-empty-alerts.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End

    It 'refuses a requires_major_bump entry missing .path rather than rendering an empty Not-fixed table'
      When call render_body state-major-bump-missing-path.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should not include '## Not fixed by this PR'
    End
  End

  Describe 'finding #6: a fatal Collateral row with an empty After renders (gone), never a blank cell'
    It 'renders (gone) in the fatal fixture, matching the corrected expected fixture'
      When call render_body state-collateral-fatal.json --collateral-note "$FX/collateral-note.txt"
      The status should be success
      The output should include '| 1.x | 1.1.18 | (gone) |'
      The output should equal "$(cat "$FX/expected-body-collateral-fatal.md")"
    End
  End

  Describe 'finding #7: EPSS always renders the number; a present field is never "unknown"'
    It 'never renders the word unknown next to an EPSS score'
      When call render_body state-scoped.json
      The status should be success
      The output should not include '| unknown |'
    End

    It 'refuses when epss_percentile is absent, rather than defaulting it to unknown or 0'
      When call render_body_g state-scoped.json group-missing-epss.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End
  End

  Describe 'finding #8: other_line_moves absent is a hard error, distinct from a legitimate null'
    It 'refuses an absent other_line_moves key'
      When call render_body state-missing-other-line-moves.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should include 'no '"'"'other_line_moves'"'"' key at all'
    End

    It 'still renders the null-baseline claim when the key is genuinely null (regression check)'
      When call render_body state-collateral-null.json
      The status should be success
      The output should include 'No baseline was available'
    End
  End

  Describe 'finding #9: commit-msg on a group missing alerts fails with the contract shape, never a partial message + bare jq exit'
    It 'exits 1 with {"error": ...} rather than jq'"'"'s own exit 5 and a half-written message'
      When call render_commit_msg_g state-scoped.json group-empty-alerts.json
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
    End
  End

  Describe 'finding #10: a Global override range is read from written[], never fabricated as N/A'
    It 'refuses when bare_override is set but written[] carries no top-level (parent: null) entry'
      When call render_body state-bare-no-range.json --global-override-note "$FX/global-override-note.txt"
      The status should equal 1
      The line 1 of output should equal '{'
      The output should include '"error"'
      The stderr should include 'render-pr:'
      The output should not include 'N/A'
    End
  End

  Describe 'labels'
    setup_mock() {
      MOCK_DIR="$SHELLSPEC_WORKDIR/render-pr-gh-mock"
      rm -rf "$MOCK_DIR"
      mkdir -p "$MOCK_DIR"
      : > "$MOCK_DIR/log"
      export MOCK_DIR
    }
    Before 'setup_mock'

    Mock gh
      printf '%s\n' "$*" >> "$MOCK_DIR/log"
      case "$1 $2 $3" in
        'label create security')
          if [ -f "$MOCK_DIR/security-fails" ]; then
            printf 'HTTP 403: Resource not accessible\n' >&2
            exit 1
          fi
          printf 'created label security\n' ;;
        'label create merge-risk:low'|'label create merge-risk:medium'|'label create merge-risk:high')
          printf 'HTTP 422: Validation Failed: name already exists\n' >&2
          exit 1 ;;
        *) printf 'unhandled: %s\n' "$*" >&2; exit 1 ;;
      esac
    End

    It 'creates security and the one merge-risk label matching the band, with the right colors and descriptions'
      When call common_jq render-pr.sh '.' labels --repo "$REPO" --band low
      The status should be success
      The output should equal '{"status":"ok","labels":["security","merge-risk:low"]}'
      The contents of file "$MOCK_DIR/log" should include 'label create security --repo octo/app --color D93F0B --description Security fix'
      The contents of file "$MOCK_DIR/log" should include 'label create merge-risk:low --repo octo/app --color 2da44e --description Low merge risk'
    End

    Describe 'band colors'
      Parameters
        low    2da44e "Low merge risk"
        medium d4a72c "Medium merge risk"
        high   cf222e "High merge risk"
      End

      It "uses $2 for merge-risk:$1"
        When call common_jq render-pr.sh '.labels[1]' labels --repo "$REPO" --band "$1"
        The status should be success
        The output should equal "\"merge-risk:$1\""
        The contents of file "$MOCK_DIR/log" should include "label create merge-risk:$1 --repo octo/app --color $2 --description $3"
      End
    End

    It 'treats "already exists" as success, never a failure'
      When call common_jq render-pr.sh '.status' labels --repo "$REPO" --band medium
      The status should be success
      The output should equal '"ok"'
    End

    It 'fails on a real gh label create error, quoting it'
      touch "$MOCK_DIR/security-fails"
      When run script "$COMMON/render-pr.sh" labels --repo "$REPO" --band low
      The status should equal 1
      The output should include 'Resource not accessible'
      The stderr should include 'Resource not accessible'
    End

    It 'rejects an unknown band'
      When run script "$COMMON/render-pr.sh" labels --repo "$REPO" --band critical
      The status should equal 1
      The output should include '"error"'
      The stderr should include 'must be low, medium, or high'
    End

    It 'threads --env-prefix in front of every gh call'
      ENV_LOG="$MOCK_DIR/env-log"
      : > "$ENV_LOG"
      cat > "$MOCK_DIR/wrapper" <<SH
#!/bin/sh
echo "wrapped: \$*" >> "$ENV_LOG"
exec "\$@"
SH
      chmod +x "$MOCK_DIR/wrapper"
      When call common_jq render-pr.sh '.status' labels --repo "$REPO" --band low --env-prefix "$MOCK_DIR/wrapper"
      The status should be success
      The output should equal '"ok"'
      The contents of file "$ENV_LOG" should include 'wrapped: gh label create security'
    End

    # Finding #11: a dispatcher's CLAUDE.md may require labels beyond
    # security and the band. `gh pr create` fails outright on a label that
    # does not already exist, so `labels` — not just `create` — has to
    # ensure them, with a neutral color since it does not know what the
    # label means.
    It 'creates every extra --label given, alongside security and the band label'
      Mock gh
        printf '%s\n' "$*" >> "$MOCK_DIR/log"
        case "$1 $2" in
          'label create') printf 'created\n' ;;
          *) printf 'unhandled: %s\n' "$*" >&2; exit 1 ;;
        esac
      End
      When call common_jq render-pr.sh '.' labels --repo "$REPO" --band low \
        --label needs-review --label breaking-change
      The status should be success
      The output should equal '{"status":"ok","labels":["security","merge-risk:low","needs-review","breaking-change"]}'
      The contents of file "$MOCK_DIR/log" should include 'label create needs-review --repo octo/app --color ededed --description'
      The contents of file "$MOCK_DIR/log" should include 'label create breaking-change --repo octo/app --color ededed --description'
    End
  End

  Describe 'create'
    setup_mock() {
      MOCK_DIR="$SHELLSPEC_WORKDIR/render-pr-create-mock"
      rm -rf "$MOCK_DIR"
      mkdir -p "$MOCK_DIR"
      : > "$MOCK_DIR/log"
      export MOCK_DIR
    }
    Before 'setup_mock'

    Mock gh
      printf '%s\n' "$*" >> "$MOCK_DIR/log"
      case "$1 $2" in
        'pr create')
          printf 'https://github.com/octo/app/pull/99\n' ;;
        *) printf 'unhandled: %s\n' "$*" >&2; exit 1 ;;
      esac
    End

    It 'passes the security and band labels, title, and body-file, with no draft flag'
      When call common_jq render-pr.sh '.' create --repo "$REPO" --head fix/dependabot-lodash-4x \
        --title 'fix(deps): resolve 2 Dependabot alert(s) for lodash 4.x' \
        --body-file "$FX/expected-body-scoped.md" --band low
      The status should be success
      The output should equal '{"status":"ok","pr_url":"https://github.com/octo/app/pull/99"}'
      The contents of file "$MOCK_DIR/log" should equal "pr create --repo octo/app --head fix/dependabot-lodash-4x --label security --label merge-risk:low --title fix(deps): resolve 2 Dependabot alert(s) for lodash 4.x --body-file $FX/expected-body-scoped.md"
      The contents of file "$MOCK_DIR/log" should not include '--draft'
    End

    It 'appends every extra --label given, after security and the band label'
      When call common_jq render-pr.sh '.' create --repo "$REPO" --head fix/dependabot-lodash-4x \
        --title t --body-file "$FX/expected-body-scoped.md" --band high \
        --label needs-review --label breaking-change
      The status should be success
      The output should equal '{"status":"ok","pr_url":"https://github.com/octo/app/pull/99"}'
      The contents of file "$MOCK_DIR/log" should equal "pr create --repo octo/app --head fix/dependabot-lodash-4x --label security --label merge-risk:high --label needs-review --label breaking-change --title t --body-file $FX/expected-body-scoped.md"
    End

    It 'fails clearly when gh pr create fails'
      Mock gh
        printf '%s\n' "$*" >> "$MOCK_DIR/log"
        printf 'a label does not exist\n' >&2
        exit 1
      End
      When run script "$COMMON/render-pr.sh" create --repo "$REPO" --head fix/dependabot-lodash-4x \
        --title t --body-file "$FX/expected-body-scoped.md" --band low
      The status should equal 1
      The output should include 'a label does not exist'
      The stderr should include 'a label does not exist'
    End

    It 'requires --body-file to name a readable file'
      When run script "$COMMON/render-pr.sh" create --repo "$REPO" --head b \
        --title t --body-file "$FX/no-such-file.md" --band low
      The status should equal 1
      The output should include '"error"'
      The stderr should include 'no such file'
    End
  End
End
